sonar.projectKey=Akash35721_Automated_Deployment_Framework_for_Al_Driven_Medical_Assistance_92bfd37d-925c-47ce-b143-31adaab30c67
sonar.projectName=Automated Deployment Framework
sonar.sources=.

sonar.exclusions=**/*.tf, .github/**/*, models/**/*.pt
